name: Test Self-Hosted Runner

on:
  push:

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show EC2 Host Info
        run: |
          echo "✅ Hello from EC2 self-hosted runner!"
          uname -a

